### ISSUE TITLE
Ennoumuが無応答になる

### ISSUE THREAD

**Issue by sibapy** [arton/ennou#15]
いつもお世話になっております。
NougakuDo 1.3.5の環境で、RailsアプリをEnnoumuで実行していると、レスポンスが返ってこなくなることがあります（Win2008 R2、SQLServer2012Express使用）。
管理者コマンドプロンプトで、rackup -s Ennoumu -p 80 で実行しています。
まれに、コマンドプロンプトでEnterを叩くと動き出すことがあります。
２プロセスで使用していますが、やがて、新たなリクエストも受け付けられなくなり、Ctrl-Cを押しても
Ennou(1.1.6) stop service for http://+:80/da pid=xxx
を表示するものの終了しません（しばらく放置するとTerminate batch job (Y/N)?が表示されます）。

ennoumu.rb に rescue を（rescue Interruptの下に）追加し backtrace を取得してみたところ、以下を延々と出力しているようです。
<pre>
#&lt;SystemCallError: unknown error - wait HttpReceiveHttpRequest (6)&gt;
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:55:in `wait'
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:55:in `block (2 levels) in run'
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:53:in `loop'
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:53:in `block in run'
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:28:in `open'
C:/**/NOUGAK~1/lib/ruby/vendor_ruby/1.9.1/rack/handler/ennoumu.rb:28:in `run'
C:/**/NOUGAK~1/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:265:in `start'
C:/**/NOUGAK~1/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:137:in `start'
C:/**/NOUGAK~1/lib/ruby/gems/1.9.1/gems/rack-1.4.1/bin/rackup:4:in `&lt;top (required)&gt;'
C:/**/NOUGAK~1/bin/rackup:23:in `load'
C:/**/NOUGAK~1/bin/rackup:23:in `&lt;main&gt;'
</pre>

なにが原因かわかりますでしょうか？
お手数ですがよろしくお願いいたします。

**Comment by kikaihonyaku** [comment]
いつもNougakuDoにお世話になっております。またクローズ後時間がたっての書き込み失礼します。

私もこちらと同様の現象がでました。
私の場合、production.logに書き込みされるタイミングでこちらのエラーがでました。
（ログに書き込まれるとエラーが毎回発生するわけではないですが、
　エラーが発生する時は必ずログが書き込まれるタイミングと同じ）

上記で書かれているassets_quiet.rbに加え、
config/environments/production.rbに「config.log_level = :fatal 」として
致命的エラー以外はproduction.logに書き込みされないようにするとほぼ発生しなくなりました。

ご報告まで。

**Comment by arton** [comment]
ご報告どうもありがとうございます。
時間を作ってログ周りを調べてみます。
